package com.app.maffan.mydaoapp.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String first_name;
    /** Not-null value. */
    private String last_name;
    /** Not-null value. */
    private String email;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String first_name, String last_name, String email) {
        this.id = id;
        this.first_name = first_name;
        this.last_name = last_name;
        this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFirst_name() {
        return first_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    /** Not-null value. */
    public String getLast_name() {
        return last_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

}
